defaults: &defaults
  docker:
    - image: circleci/node:8.11.3-browsers

aliases:
  - &restore-cache
    keys:
      - v1-dependencies-{{ checksum "package.json" }}
      - v1-dependencies-

  - &save-cache
    paths:
      - node_modules
      - ~/.meteor
      - ~/.npm
    key: v1-dependencies-{{ checksum "package.json" }}

  - &install-meteor |
    curl https://install.meteor.com | /bin/sh
  
  - &run-e2e-tests |
    sleep 100 # Wait for app to run before starting e2e tests.
    meteor npm run test-e2e

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: npm install
      - save_cache: *save-cache
      - run: *install-meteor
      - run: npm test
      - run:
          command: meteor npm run dev
          background: true
      - run: *run-e2e-tests
  stage:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: npm install
      - save_cache: *save-cache
      - run: *install-meteor
      - run: npm test
      - run:
          command: meteor npm run dev
          background: true
      - run: *run-e2e-tests
      # - run: npm run staging
  deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: npm install
      - save_cache: *save-cache
      - run: *install-meteor
      - run: npm test
      - run:
          command: meteor npm run dev
          background: true
      - run: *run-e2e-tests
      # - run: npm run production

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - /feature\/.*/
                - /refactor\/.*/
                - /bug\/.*/
                - /chore\/.*/
      - stage:
          filters:
            branches:
              only:
                - development
      - deploy:
          filters:
            branches:
              only:
                - master
