query events {
  events {
    _id
    customerId
    actions {
      status
      type
    }
    actionParameters {
      username
      ipAddress
      domain
      instanceId
      vpcId
    }
    guardDutyEvent
  }
}
