query events($perPage: Int!, $currentPage: Int!) {
  events(perPage: $perPage, currentPage: $currentPage) {
    totalEvents
    events {
      _id
      customerId
      actions {
        status
        type
        isReversible
      }
      actionParameters {
        username
        ipAddress
        domain
        instanceId
        vpcId
      }
      guardDutyEvent
    }
  }
}
